stages:
  - build
  - publish
  - deploy

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

build:
  stage: build
  script:
    - cd python
    - docker build -t $DOCKER_IMAGE .
  only:
    - main

publish:
  stage: publish
  script:
    - docker push $DOCKER_IMAGE
  only:
    - main

deploy:
  stage: deploy
  script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan $DEPLOY_SERVER >> ~/.ssh/known_hosts
    - ssh $DEPLOY_USER@$DEPLOY_SERVER "git clone $CI_REPOSITORY_URL || (cd $(basename "$CI_REPOSITORY_URL" .git) && git pull)"
    - ssh $DEPLOY_USER@$DEPLOY_SERVER "cd $(basename "$CI_REPOSITORY_URL" .git) && docker-compose pull && docker-compose up -d"
  only:
    - main
