global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'flask-app'
    static_configs:
      - targets: ['flask-app:5000']

rule_files:
  - /etc/prometheus/alert.rules.yml